### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by budaLi** [Hsintao/pfld_106_face_landmarks#1]
看到你的数据集挺大的，就想先问下你用的是京东的106点lapa数据集嘛,期待你的回复~

**Comment by Hsintao** [comment]
@budaLi 不好意思 没听过lapa这个数据集 但是我手中确实有一份jd的106脸关键点数据，这个仓库里的数据集是我从GitHub找的

**Comment by Hsintao** [comment]
@budaLi 需要的话  请自取  链接:https://pan.baidu.com/s/1h2_ZyZbnejSteviWRixYPw 密码:jfzd

**Comment by budaLi** [comment]
感谢回复~ 祝好运

**Comment by budaLi** [comment]
您好~ 我下载了您百度云提供的三个数据集，看到里面的图片没有标注，有两个疑问。1：图片是从哪里获取的？是结合了所有的关键点数据集图片吗？包含wflw，300w等嘛？   2.标注接口使用face++是嘛

**Comment by Hsintao** [comment]
> 您好~ 我下载了您百度云提供的三个数据集，看到里面的图片没有标注，有两个疑问。1：图片是从哪里获取的？是结合了所有的关键点数据集图片吗？包含wflw，300w等嘛？ 2.标注接口使用face++是嘛

我这份数据集是从github找的  您可以根据我data文件夹下的readme找到相关信息， 图片标注文件也在data文件夹下
